version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: products-frontend
    volumes:
      - ./app:/var/www/html/app
      - ./config/dev/virtualhosts/products.dev.com:/etc/nginx/sites-enabled/products.dev.com
      - ./config/dev/virtualhosts/urls.js:/var/www/html/app/public_html/config/urls.js
    ports:
      - "80:80"